### ISSUE TITLE
Zero: Black screen when finish choose the song

### ISSUE THREAD

**Issue by cuongnguyenduc0511** [pumpitupdev/pumptools#51]
# Bug report

## Description
I've used pumpos to mount PIU Zero game **(single game test)** and test with my MK9. Gameplay no problem, but whenever I finish choosing song, I expect it should show the song thumbnail (title card) for 5 seconds, but reality it shows black screen instead. You could check my video below

https://youtu.be/zWm9eV5SrKI

Note: This issue occurs in CREDIT MODE, I tested FREE PLAY mode, it doesn't not show black screen

## Affected games and versions
17_zero (build 1.03)

## Pumptools versions tested

1.12?? (I cloned the latest source code of pumptools - branch `master` - generate pumptools.zip with `make build-docker` - just yesterday) 

## OS and hardware specs

* OS: Ubuntu 18.04 LTS (when I implement mount the pumpos and game: 17_zero)
* CPU: Core 2 Duo E8400 3.00Ghz
* RAM: 8GB DDR3 (2x4 dual channel) 
* Mainboard: FOXCONN G41MXE-V
* GPU: NVIDIA Geforce G210
* Controllers/IO: Official PIUIO (old)

**Comment by voidderef** [comment]
Hey thanks for reaching out and providing all the information. So far, I have never heard or seen this issue before.

Does this only happen on Zero? It might be good to know if this also happens on other games of the same generation, e.g. exceed 2, nx and also next generation (nx2, nxa) games. Also, using pumptools master might be the latest but not released yet changes. If you could manually download [1.11](https://drive.google.com/file/d/1Nz9AzE1-qlhNTlo5BapYEw_stIv_G4wH/view) latest compiled binaries and test these, that would also provide some more information regarding when this might have gone wrong.

Also pointing out that I have not had a lot of time in the last months to work on this. I appreciate the feedback as it might help me once I have spare time to pick up some work on this again or someone else who wants to continue to fix any outstanding bugs and understand existing problems with the current state.

**Comment by cuongnguyenduc0511** [comment]
@voidderef it is weird that the issue I test today is not happening anymore, and it's hard to reproduce the issue step by step. I will test it again with 1.11 build then. I might close this issue
