### ISSUE TITLE
NX2 Doesn't open

### ISSUE THREAD

**Issue by Getze56901** [pumpitupdev/pumptools#52]
# Bug report
NX2 Doesn't open the game
## Description
The game doesn't open and send this command line
](https://cdn.discordapp.com/attachments/814772510024925224/1059669092258299914/image.png)

## Affected games and versions
NX2

## Pumptools versions tested
1.12

## OS and hardware specs

* OS:UBUNTU 
* CPU:INTEL I5 11400H 
* RAM: 16 GB
* GPU: GeForce RTX 3050TI 
* Controllers/IO Keyboard:

**Comment by concubidated** [comment]
Is the data correctly setup? Looks like the piu binary is missing? Can you show the contents of your nx2 directory?
![image](https://user-images.githubusercontent.com/1231328/210443393-ec5d7877-a793-4d04-a990-a915b3a2729e.png)

**Comment by voidderef** [comment]
> Is the data correctly setup? Looks like the piu binary is missing. Can you show the contents of your nx2 directory? ![image](https://user-images.githubusercontent.com/1231328/210443393-ec5d7877-a793-4d04-a990-a915b3a2729e.png)

To be even more specific, can you run the following commands and paste the output here?

```sh
ls -la /mnt/hgfs/20_nx2
```

```sh
ls -la /mnt/hgfs
```

Also, please post how you run the game, full command, plus the full output of what appears to be `piueb` that you are running. It should create a logfile called `piueb.log` iirc.

It also appears, due to the `hgfs` folder, that you are accessing your note via a shared network mount, is that correct? Bringing this up to let you know that, at least myself, have never run nor tested these games from a network mounted folder. Theoretically, it should not matter, but experience over the years has shown that network mounts always create issues with weird symptoms. I advice to move the data to your local disk first, verify you get the game to run, then try moving it to the network mount and see if that also works. That might save you a lot of time and frustartion if you run into issues because of that.

**Comment by piotr25691** [comment]
> > Is the data correctly setup? Looks like the piu binary is missing. Can you show the contents of your nx2 directory? ![image](https://user-images.githubusercontent.com/1231328/210443393-ec5d7877-a793-4d04-a990-a915b3a2729e.png)
> 
> To be even more specific, can you run the following commands and paste the output here?
> 
> ```shell
> ls -la /mnt/hgfs/20_nx2
> ```
> 
> ```shell
> ls -la /mnt/hgfs
> ```
> 
> Also, please post how you run the game, full command, plus the full output of what appears to be `piueb` that you are running. It should create a logfile called `piueb.log` iirc.
> 
> It also appears, due to the `hgfs` folder, that you are accessing your note via a shared network mount, is that correct? Bringing this up to let you know that, at least myself, have never run nor tested these games from a network mounted folder. Theoretically, it should not matter, but experience over the years has shown that network mounts always create issues with weird symptoms. I advice to move the data to your local disk first, verify you get the game to run, then try moving it to the network mount and see if that also works. That might save you a lot of time and frustartion if you run into issues because of that.

On the offchance, I got a window popping up only to say "WAITING LOCK DEVICE... PLEASE CHECK ATTACHED LOCK DEVICE IS INSTALLED CORRECTLY"

**Comment by piotr25691** [comment]
> > > Is the data correctly setup? Looks like the piu binary is missing. Can you show the contents of your nx2 directory? ![image](https://user-images.githubusercontent.com/1231328/210443393-ec5d7877-a793-4d04-a990-a915b3a2729e.png)
> > 
> > 
> > To be even more specific, can you run the following commands and paste the output here?
> > ```shell
> > ls -la /mnt/hgfs/20_nx2
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```shell
> > ls -la /mnt/hgfs
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Also, please post how you run the game, full command, plus the full output of what appears to be `piueb` that you are running. It should create a logfile called `piueb.log` iirc.
> > It also appears, due to the `hgfs` folder, that you are accessing your note via a shared network mount, is that correct? Bringing this up to let you know that, at least myself, have never run nor tested these games from a network mounted folder. Theoretically, it should not matter, but experience over the years has shown that network mounts always create issues with weird symptoms. I advice to move the data to your local disk first, verify you get the game to run, then try moving it to the network mount and see if that also works. That might save you a lot of time and frustartion if you run into issues because of that.
> 
> On the offchance, I got a window popping up only to say "WAITING LOCK DEVICE... PLEASE CHECK ATTACHED LOCK DEVICE IS INSTALLED CORRECTLY", how do I fix that?

Have these logs to check what did I screw up causing the game to give me what appears to be a dongle error:

[piueb.log](https://github.com/pumpitupdev/pumptools/files/10346644/piueb.log)
[pumptools.log](https://github.com/pumpitupdev/pumptools/files/10346646/pumptools.log)

**Comment by voidderef** [comment]
> > > > Is the data correctly setup? Looks like the piu binary is missing. Can you show the contents of your nx2 directory? ![image](https://user-images.githubusercontent.com/1231328/210443393-ec5d7877-a793-4d04-a990-a915b3a2729e.png)
> > > 
> > > 
> > > To be even more specific, can you run the following commands and paste the output here?
> > > ```shell
> > > ls -la /mnt/hgfs/20_nx2
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > ```shell
> > > ls -la /mnt/hgfs
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Also, please post how you run the game, full command, plus the full output of what appears to be `piueb` that you are running. It should create a logfile called `piueb.log` iirc.
> > > It also appears, due to the `hgfs` folder, that you are accessing your note via a shared network mount, is that correct? Bringing this up to let you know that, at least myself, have never run nor tested these games from a network mounted folder. Theoretically, it should not matter, but experience over the years has shown that network mounts always create issues with weird symptoms. I advice to move the data to your local disk first, verify you get the game to run, then try moving it to the network mount and see if that also works. That might save you a lot of time and frustartion if you run into issues because of that.
> > 
> > 
> > On the offchance, I got a window popping up only to say "WAITING LOCK DEVICE... PLEASE CHECK ATTACHED LOCK DEVICE IS INSTALLED CORRECTLY", how do I fix that?
> 
> Have these logs and screenshots to check what did I screw up causing the game to give me what appears to be a dongle error:
> 
> [piueb.log](https://github.com/pumpitupdev/pumptools/files/10346644/piueb.log) [pumptools.log](https://github.com/pumpitupdev/pumptools/files/10346646/pumptools.log)
> 
> ![image](https://camo.githubusercontent.com/3db546af5601ad2a301c35219580cac8ccb4bcbdad7ef693776e62f0cf30c151/68747470733a2f2f63646e2e646973636f72646170702e636f6d2f6174746163686d656e74732f3338323137373230373835313934313838392f313036303236313734313737363335353337382f696d6167652e706e67)

The log doesn't show any errors or anything odd looking. The dongle requests also seem to be dispatched successfully by pumptools. This doesn't mean that decryption suceeds as the emulation is operating on a rainbow table.

What's the version of NX2 you are trying to run? Where did you source the data from?

The only supported version is 1.54 as outlined by [the documentation](https://github.com/pumpitupdev/pumptools#games-and-latest-versions-supported)

**Comment by piotr25691** [comment]
> > > > > Is the data correctly setup? Looks like the piu binary is missing. Can you show the contents of your nx2 directory? ![image](https://user-images.githubusercontent.com/1231328/210443393-ec5d7877-a793-4d04-a990-a915b3a2729e.png)
> > > > 
> > > > 
> > > > To be even more specific, can you run the following commands and paste the output here?
> > > > ```shell
> > > > ls -la /mnt/hgfs/20_nx2
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > ```shell
> > > > ls -la /mnt/hgfs
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > Also, please post how you run the game, full command, plus the full output of what appears to be `piueb` that you are running. It should create a logfile called `piueb.log` iirc.
> > > > It also appears, due to the `hgfs` folder, that you are accessing your note via a shared network mount, is that correct? Bringing this up to let you know that, at least myself, have never run nor tested these games from a network mounted folder. Theoretically, it should not matter, but experience over the years has shown that network mounts always create issues with weird symptoms. I advice to move the data to your local disk first, verify you get the game to run, then try moving it to the network mount and see if that also works. That might save you a lot of time and frustartion if you run into issues because of that.
> > > 
> > > 
> > > On the offchance, I got a window popping up only to say "WAITING LOCK DEVICE... PLEASE CHECK ATTACHED LOCK DEVICE IS INSTALLED CORRECTLY", how do I fix that?
> > 
> > 
> > Have these logs and screenshots to check what did I screw up causing the game to give me what appears to be a dongle error:
> > [piueb.log](https://github.com/pumpitupdev/pumptools/files/10346644/piueb.log) [pumptools.log](https://github.com/pumpitupdev/pumptools/files/10346646/pumptools.log)
> > ![image](https://camo.githubusercontent.com/3db546af5601ad2a301c35219580cac8ccb4bcbdad7ef693776e62f0cf30c151/68747470733a2f2f63646e2e646973636f72646170702e636f6d2f6174746163686d656e74732f3338323137373230373835313934313838392f313036303236313734313737363335353337382f696d6167652e706e67)
> 
> The log doesn't show any errors or anything odd looking. The dongle requests also seem to be dispatched successfully by pumptools. This doesn't mean that decryption suceeds as the emulation is operating on a rainbow table.
> 
> What's the version of NX2 you are trying to run? Where did you source the data from?
> 
> The only supported version is 1.54 as outlined by [the documentation](https://github.com/pumpitupdev/pumptools#games-and-latest-versions-supported)

Well, the version is in fact 1.54 when I looked back into the data link I got, so I don't know what is exactly happening. There must be something else going wrong.

**Comment by voidderef** [comment]
> > > > > > Is the data correctly setup? Looks like the piu binary is missing. Can you show the contents of your nx2 directory? ![image](https://user-images.githubusercontent.com/1231328/210443393-ec5d7877-a793-4d04-a990-a915b3a2729e.png)
> > > > > 
> > > > > 
> > > > > To be even more specific, can you run the following commands and paste the output here?
> > > > > ```shell
> > > > > ls -la /mnt/hgfs/20_nx2
> > > > > ```
> > > > > 
> > > > > 
> > > > >     
> > > > >       
> > > > >     
> > > > > 
> > > > >       
> > > > >     
> > > > > 
> > > > >     
> > > > >   
> > > > > ```shell
> > > > > ls -la /mnt/hgfs
> > > > > ```
> > > > > 
> > > > > 
> > > > >     
> > > > >       
> > > > >     
> > > > > 
> > > > >       
> > > > >     
> > > > > 
> > > > >     
> > > > >   
> > > > > Also, please post how you run the game, full command, plus the full output of what appears to be `piueb` that you are running. It should create a logfile called `piueb.log` iirc.
> > > > > It also appears, due to the `hgfs` folder, that you are accessing your note via a shared network mount, is that correct? Bringing this up to let you know that, at least myself, have never run nor tested these games from a network mounted folder. Theoretically, it should not matter, but experience over the years has shown that network mounts always create issues with weird symptoms. I advice to move the data to your local disk first, verify you get the game to run, then try moving it to the network mount and see if that also works. That might save you a lot of time and frustartion if you run into issues because of that.
> > > > 
> > > > 
> > > > On the offchance, I got a window popping up only to say "WAITING LOCK DEVICE... PLEASE CHECK ATTACHED LOCK DEVICE IS INSTALLED CORRECTLY", how do I fix that?
> > > 
> > > 
> > > Have these logs and screenshots to check what did I screw up causing the game to give me what appears to be a dongle error:
> > > [piueb.log](https://github.com/pumpitupdev/pumptools/files/10346644/piueb.log) [pumptools.log](https://github.com/pumpitupdev/pumptools/files/10346646/pumptools.log)
> > > ![image](https://camo.githubusercontent.com/3db546af5601ad2a301c35219580cac8ccb4bcbdad7ef693776e62f0cf30c151/68747470733a2f2f63646e2e646973636f72646170702e636f6d2f6174746163686d656e74732f3338323137373230373835313934313838392f313036303236313734313737363335353337382f696d6167652e706e67)
> > 
> > 
> > The log doesn't show any errors or anything odd looking. The dongle requests also seem to be dispatched successfully by pumptools. This doesn't mean that decryption suceeds as the emulation is operating on a rainbow table.
> > What's the version of NX2 you are trying to run? Where did you source the data from?
> > The only supported version is 1.54 as outlined by [the documentation](https://github.com/pumpitupdev/pumptools#games-and-latest-versions-supported)
> 
> Well, the version is in fact 1.54 when I looked back into the data link I got, so I don't know what is exactly happening. There must be something else going wrong.

Do you have other versions like NX or NXA that you can test?
What's your ubuntu and kernel version?

**Comment by piotr25691** [comment]
> > > > > > > Is the data correctly setup? Looks like the piu binary is missing. Can you show the contents of your nx2 directory? ![image](https://user-images.githubusercontent.com/1231328/210443393-ec5d7877-a793-4d04-a990-a915b3a2729e.png)
> > > > > > 
> > > > > > 
> > > > > > To be even more specific, can you run the following commands and paste the output here?
> > > > > > ```shell
> > > > > > ls -la /mnt/hgfs/20_nx2
> > > > > > ```
> > > > > > 
> > > > > > 
> > > > > >     
> > > > > >       
> > > > > >     
> > > > > > 
> > > > > >       
> > > > > >     
> > > > > > 
> > > > > >     
> > > > > >   
> > > > > > ```shell
> > > > > > ls -la /mnt/hgfs
> > > > > > ```
> > > > > > 
> > > > > > 
> > > > > >     
> > > > > >       
> > > > > >     
> > > > > > 
> > > > > >       
> > > > > >     
> > > > > > 
> > > > > >     
> > > > > >   
> > > > > > Also, please post how you run the game, full command, plus the full output of what appears to be `piueb` that you are running. It should create a logfile called `piueb.log` iirc.
> > > > > > It also appears, due to the `hgfs` folder, that you are accessing your note via a shared network mount, is that correct? Bringing this up to let you know that, at least myself, have never run nor tested these games from a network mounted folder. Theoretically, it should not matter, but experience over the years has shown that network mounts always create issues with weird symptoms. I advice to move the data to your local disk first, verify you get the game to run, then try moving it to the network mount and see if that also works. That might save you a lot of time and frustartion if you run into issues because of that.
> > > > > 
> > > > > 
> > > > > On the offchance, I got a window popping up only to say "WAITING LOCK DEVICE... PLEASE CHECK ATTACHED LOCK DEVICE IS INSTALLED CORRECTLY", how do I fix that?
> > > > 
> > > > 
> > > > Have these logs and screenshots to check what did I screw up causing the game to give me what appears to be a dongle error:
> > > > [piueb.log](https://github.com/pumpitupdev/pumptools/files/10346644/piueb.log) [pumptools.log](https://github.com/pumpitupdev/pumptools/files/10346646/pumptools.log)
> > > > ![image](https://camo.githubusercontent.com/3db546af5601ad2a301c35219580cac8ccb4bcbdad7ef693776e62f0cf30c151/68747470733a2f2f63646e2e646973636f72646170702e636f6d2f6174746163686d656e74732f3338323137373230373835313934313838392f313036303236313734313737363335353337382f696d6167652e706e67)
> > > 
> > > 
> > > The log doesn't show any errors or anything odd looking. The dongle requests also seem to be dispatched successfully by pumptools. This doesn't mean that decryption suceeds as the emulation is operating on a rainbow table.
> > > What's the version of NX2 you are trying to run? Where did you source the data from?
> > > The only supported version is 1.54 as outlined by [the documentation](https://github.com/pumpitupdev/pumptools#games-and-latest-versions-supported)
> > 
> > 
> > Well, the version is in fact 1.54 when I looked back into the data link I got, so I don't know what is exactly happening. There must be something else going wrong.
> 
> Do you have other versions like NX or NXA that you can test? What's your ubuntu and kernel version?

I do not. I'm running Ubuntu 22.04 LTS on the 5.15 kernel

**Comment by voidderef** [comment]
> > > > > > > > Is the data correctly setup? Looks like the piu binary is missing. Can you show the contents of your nx2 directory? ![image](https://user-images.githubusercontent.com/1231328/210443393-ec5d7877-a793-4d04-a990-a915b3a2729e.png)
> > > > > > > 
> > > > > > > 
> > > > > > > To be even more specific, can you run the following commands and paste the output here?
> > > > > > > ```shell
> > > > > > > ls -la /mnt/hgfs/20_nx2
> > > > > > > ```
> > > > > > > 
> > > > > > > 
> > > > > > >     
> > > > > > >       
> > > > > > >     
> > > > > > > 
> > > > > > >       
> > > > > > >     
> > > > > > > 
> > > > > > >     
> > > > > > >   
> > > > > > > ```shell
> > > > > > > ls -la /mnt/hgfs
> > > > > > > ```
> > > > > > > 
> > > > > > > 
> > > > > > >     
> > > > > > >       
> > > > > > >     
> > > > > > > 
> > > > > > >       
> > > > > > >     
> > > > > > > 
> > > > > > >     
> > > > > > >   
> > > > > > > Also, please post how you run the game, full command, plus the full output of what appears to be `piueb` that you are running. It should create a logfile called `piueb.log` iirc.
> > > > > > > It also appears, due to the `hgfs` folder, that you are accessing your note via a shared network mount, is that correct? Bringing this up to let you know that, at least myself, have never run nor tested these games from a network mounted folder. Theoretically, it should not matter, but experience over the years has shown that network mounts always create issues with weird symptoms. I advice to move the data to your local disk first, verify you get the game to run, then try moving it to the network mount and see if that also works. That might save you a lot of time and frustartion if you run into issues because of that.
> > > > > > 
> > > > > > 
> > > > > > On the offchance, I got a window popping up only to say "WAITING LOCK DEVICE... PLEASE CHECK ATTACHED LOCK DEVICE IS INSTALLED CORRECTLY", how do I fix that?
> > > > > 
> > > > > 
> > > > > Have these logs and screenshots to check what did I screw up causing the game to give me what appears to be a dongle error:
> > > > > [piueb.log](https://github.com/pumpitupdev/pumptools/files/10346644/piueb.log) [pumptools.log](https://github.com/pumpitupdev/pumptools/files/10346646/pumptools.log)
> > > > > ![image](https://camo.githubusercontent.com/3db546af5601ad2a301c35219580cac8ccb4bcbdad7ef693776e62f0cf30c151/68747470733a2f2f63646e2e646973636f72646170702e636f6d2f6174746163686d656e74732f3338323137373230373835313934313838392f313036303236313734313737363335353337382f696d6167652e706e67)
> > > > 
> > > > 
> > > > The log doesn't show any errors or anything odd looking. The dongle requests also seem to be dispatched successfully by pumptools. This doesn't mean that decryption suceeds as the emulation is operating on a rainbow table.
> > > > What's the version of NX2 you are trying to run? Where did you source the data from?
> > > > The only supported version is 1.54 as outlined by [the documentation](https://github.com/pumpitupdev/pumptools#games-and-latest-versions-supported)
> > > 
> > > 
> > > Well, the version is in fact 1.54 when I looked back into the data link I got, so I don't know what is exactly happening. There must be something else going wrong.
> > 
> > 
> > Do you have other versions like NX or NXA that you can test? What's your ubuntu and kernel version?
> 
> ~I do not. I'm running Ubuntu 22.04 LTS on the 5.15 kernel~
> 
> I fixed the problem by using Ubuntu 20.04 LTS instead

I was about to answer that I never tested anything never than 18.04 LTS and I am still running that version. Therefore, I have no idea if any changes on the OS, libraries or the kernel might have introduced new issues.

Still, thanks for letting me know that 20.04 LTS works (as well). Will update the documentation accordingly with a note for now.

**Comment by Getze56901** [comment]
> 
Tested in 20.04 LTS and i have the dongle error
[pumptools.log](https://github.com/pumpitupdev/pumptools/files/10366946/pumptools.log)
[piueb.log](https://github.com/pumpitupdev/pumptools/files/10366947/piueb.log)

![0](https://user-images.githubusercontent.com/88003612/211165114-75bd4c3e-4511-440d-a66f-36f82dca7ad9.png)

**Comment by piotr25691** [comment]
> > 
> 
> Tested in 20.04 LTS and i have the dongle error [pumptools.log](https://github.com/pumpitupdev/pumptools/files/10366946/pumptools.log) [piueb.log](https://github.com/pumpitupdev/pumptools/files/10366947/piueb.log)
> 
> ![0](https://user-images.githubusercontent.com/88003612/211165114-75bd4c3e-4511-440d-a66f-36f82dca7ad9.png)

While this does not cause the issue, you are also missing the `libasound2-plugins` package.

Please run `sudo apt install libasound2-plugins` to resolve an error in the log.

**Comment by voidderef** [comment]
> > 
> 
> Tested in 20.04 LTS and i have the dongle error [pumptools.log](https://github.com/pumpitupdev/pumptools/files/10366946/pumptools.log) [piueb.log](https://github.com/pumpitupdev/pumptools/files/10366947/piueb.log)
> 
> ![0](https://user-images.githubusercontent.com/88003612/211165114-75bd4c3e-4511-440d-a66f-36f82dca7ad9.png)

Checking the logs for errors, you are apparently not running it as root, which is a requirement for many parts of the game itself.

```
[E][2023/01/07-12:19:44:330] Running as non-root user, game likely to crash!
```

```
[E][2023/1/7-12:19:44:558][hook-core-piu-utils][piu-utils.c:110] Process not running as root which is required for the game to work correctly.
```

Please pay attention to what the log output is saying. This message is there for a good reason.

Further errors are clearly pointing towards stuff going wrong:

```
[E][2023/1/7-12:19:44:560][patch-usb-mnt][usb-mnt.c:20] Creating directory /mnt/0 failed
[E][2023/1/7-12:19:44:560][patch-usb-mnt][usb-mnt.c:26] Creating invalid indicator file /mnt/0/invalid failed
...
[E][2023/1/7-12:19:44:560][patch-usb-mnt][usb-mnt.c:20] Creating directory /mnt/1 failed
[E][2023/1/7-12:19:44:560][patch-usb-mnt][usb-mnt.c:26] Creating invalid indicator file /mnt/1/invalid failed
...
[E][2023/1/7-12:19:44:567][sec-microdog40d][microdog40d.c:67] Binding socket failed: No such file or directory
```

And there is also clearly an error with the dongle part `sec-microdog40d`.
